name: Azure DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Tf init
        run: |
          terraform init -backend-config="provider=azurerm&command=init&backendServiceArm=Freesub(8337a852-3759-476f-97d1-2350df1ae26b)&backendAzureRmResourceGroupName=tfvmex-resources&backendAzureRmStorageAccountName=ibrahimtech&backendAzureRmContainerName=ibrahim-tfstate&backendAzureRmKey=prod.terraform.tfstate"
      - name: Tf validate
        run: |
          terraform validate
      - name: Tf fmt
        run: |
          terraform fmt
      - name: Tf plan
        run: |
          terraform plan
      - name: Archive files
        run: |
          zip -r $(Build.SourcesDirectory)/ $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      - name: Publish build artifacts
        uses: actions/upload-artifact@v2
        with:
          path: $(Build.ArtifactStagingDirectory)
          artifact-name: $(Build.BuildId)-build
